version: "3"
services:
  go-api:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      GO111MODULE: "on"
      ENVIRONMENT: "DEV"
    ports:
      - '5555:5555'
    volumes:
      - ./:/app
