version: "3.6"
services:
  goservice:
    build:
      context: "."
      dockerfile: "Dockerfile.production"
    ports:
      - "5555"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "goservice"
