FROM golang:1.18-alpine AS builder
RUN mkdir /out
ADD . /out/
WORKDIR /out
RUN go build -o webapp

FROM alpine
RUN adduser -S -D -H -h /app appuser
USER appuser
COPY --from=builder /out/webapp /app/
COPY web/ /app/web
WORKDIR /app
CMD ["./webapp"]
