version: "3.6"
services:
  goservice:
    build:
      context: "."
      dockerfile: "Dockerfile.production"
    environment:
      ENVIRONMENT: "PROD"
    ports:
      - "5555"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "goservice"
    volumes:
      - ./web:/var/www/web
